apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb-rs
  template:
    metadata:
      labels:
        app: myweb-rs
    spec:
      containers:
      - name: myweb
        image: ghcr.io/c1t1d0s7/go-myweb
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M